name: hexcap
url: http://hexcap.org
description: An interactive hex editor for libpcap files 

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
