name: hexcap
url: http://hexcap.org
description: An interactive hex editor for PCAP files 

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
